export const en = {
  "hintText": {
    "fileName": "Enter File Name",
    "alias": "Enter Display Name",
    "newItem": "+ New",
    "selectNote": "Select Note...",
    "createListItem": "Create List Item",
    "dragDropProperties": "Drag and drop to reorder properties",
    "dragDropModifierKeys": "Hold Shift to select multiple items",
    "hiddenExtensionsPlaceholder": "e.g., .mdb, _assets, _blocks"
  },
  "timeUnits": {
    "hour": "Hour",
    "day": "Day",
    "week": "Week",
    "month": "Month",
    "year": "Year",
    "minute": "Minute",
    "second": "Second"
  },
  "aggregates": {
    "values": "Values",
    "sum": "Sum",
    "average": "Average",
    "median": "Median",
    "count": "Count",
    "countValues": "Count Values",
    "countUniques": "Count Uniques",
    "percentageEmpty": "Percentage Empty",
    "percentageNotEmpty": "Percentage Not Empty",
    "min": "Min",
    "max": "Max",
    "range": "Range",
    "empty": "Empty",
    "notEmpty": "Not Empty",
    "earliest": "Earliest",
    "latest": "Latest",
    "complete": "Complete",
    "incomplete": "Not Complete",
    "percentageComplete": "Percentage Complete",
    "dateRange": "Date Range"
  },
  "fieldTypes": {
    "object": "Object",
    "text": "Text",
    "file": "File",
    "date": "Date",
    "number": "Number"
  },
  "defaults": {
    "spaceNote": "Current Note",
    "spaceContext": "Current Space"
  },
  "commands": {
    "h1": "Heading 1",
    "h2": "Heading 2",
    "h3": "Heading 3",
    "h4": "Heading 4",
    "h5": "Heading 5",
    "h6": "Heading 6",
    "columns": "Columns",
    "tabs": "Tabs",
    "button": "Button",
    "label": "Label",
    "column": "Column",
    "idea": "New",
    "group": "Group",
    "paragraph": "Text",
    "card": "Card",
    "cardDesc": "Card container with styled background",
    "progress": "Progress",
    "rating": "Rating",
    "circularProgress": "Circular Progress",
    "list": "Bullet List",
    "ordered-list": "Numbered List",
    "todo": "To-do List",
    "quote": "Quote",
    "internal": "Link to Note",
    "context": "Embed Existing Context",
    "flowEmbed": "Embed Note or Space",
    "board": "New Board",
    "divider": "Divider",
    "note": "Note Block",
    "link": "Web Link",
    "internalLink": "Link",
    "callout": "Callout",
    "bookmark": "Bookmark",
    "table": "New Table",
    "codeblock": "Code Block",
    "toggle": "Toggle",
    "emoji": "Emoji",
    "image": "Image",
    "chart": "Chart",
    "newNote": "Note",
    "tag": "Tag",
    "makeMenu": "Flow Menu",
    "selectStyle": "Style",
    "toggleKeyboard": "Toggle Keyboard",
    "flow": "Flow"
  },
  "styles": {
    "blocklink": "Link to Note",
    "textColor": "Text Color",
    "highlight": "Highlight"
  },
  "commandsSuggest": {
    "noResult": "No result"
  },
  "commandPalette": {
    "toggleEnhancedLogs": "Toggle Enhanced Logs",
    "fixPathCharacters": "Fix Path Characters",
    "moveSpaceDataFolder": "Move Space Data Folder",
    "openFlow": "Open Flow Blocks in Selection",
    "closeFlow": "Close Flow Blocks in Selection",
    "openSpaces": "Open Navigator",
    "blink": "Blink",
    "revealFile": "Reveal File in Navigator",
    "releaseNotes": "Release Notes",
    "getStarted": "Get Started",
    "toggleBacklinks": "Toggle Backlinks",
    "pinActiveFileToSpace": "Pin Active File to Space",
    "closeExtraFileTabs": "Close Extra File Tabs",
    "convertPathToSpace": "Convert Path to Space",
    "openFileContext": "Open File Context"
  },
  "frames": {
    "label": {
      "label": "Label",
      "description": "Label"
    },
    "context": {
      "label": "Context",
      "description": "Display a context view from another space"
    },
    "calendar": {
      "label": "Calendar View"
    },
    "event": {
      "label": "Event"
    },
    "divider": {
      "label": "Divider",
      "description": "Divider to separate your content"
    },
    "button": {
      "label": "Button",
      "description": "Buttons can perform actions and open links"
    },
    "toggle": {
      "description": "Toggle to show/hide content"
    }
  },
  "menu": {
    "createItemInSpace": "Create Item in Space",
    "newItemView": "New Item View",
    "noActionsAvailable": "No Actions Available",
    "path": "Path",
    "name": "Name",
    "content": "Content",
    "property": "Property",
    "value": "Value",
    "table": "Table",
    "click": "Click",
    "hover": "Hover",
    "align": "Align",
    "shadow": "Shadow",
    "noFramesAvailable": "No Frames Available",
    "tabName": "Tab Name",
    "removeTab": "Remove Tab",
    "items": "Items",
    "metadata": "Metadata",
    "special": "Special",
    "cardContainerWithStyledBackground": "Card Container With Styled Background",
    "buttonContainerWithStyledAppearance": "Button Container With Styled Appearance",
    "up": "Up",
    "down": "Down",
    "selectmenu": "Selectmenu",
    "toggle": "Toggle",
    "setDefaultSticker": "Set Default Sticker",
    "new": "New",
    "noColorPalettesAvailable": "No Color Palettes Available",
    "stopPosition": "Stop Position",
    "removeSelectedGradientStop": "Remove Selected Gradient Stop",
    "noColor": "No Color",
    "thisElementWillHaveNoColorApplied": "This Element Will Have No Color Applied",
    "yes": "Yes",
    "no": "No",
    "barChart": "Bar Chart",
    "lineChart": "Line Chart",
    "scatterPlot": "Scatter Plot",
    "pieChart": "Pie Chart",
    "areaChart": "Area Chart",
    "radarChart": "Radar Chart",
    "space": "Space",
    "list": "List",
    "category": "Category",
    "values": "Values",
    "xAxisField": "X-Axis Field",
    "yAxisFields": "Y-Axis Fields",
    "selectDataSource": "Select a data source",
    "selectCategoryField": "Select category field",
    "selectXAxisField": "Select X-axis field",
    "selectValueFields": "Select value fields",
    "selectYAxisFields": "Select Y-axis fields",
    "legend": "Legend",
    "hidden": "Hidden",
    "hideLegend": "Hide Legend",
    "showLegend": "Show Legend",
    "legendPosition": "Position",
    "orientation": "Orientation",
    "horizontal": "Horizontal",
    "vertical": "Vertical",
    "legendTop": "Top",
    "legendBottom": "Bottom",
    "legendLeft": "Left",
    "legendRight": "Right",
    "colorPalette": "Color Palette",
    "defaultPalette": "Default",
    "axisLabels": "Labels",
    "groupBy": "Group By",
    "aggregate": "Aggregate",
    "count": "Count",
    "sum": "Sum",
    "average": "Average",
    "min": "Min",
    "max": "Max",
    "distinct": "Distinct",
    "editFormula": "Edit Formula",
    "right": "Right",
    "showXAxis": "Show X Axis",
    "showXAxisTitle": "Show X Axis Title",
    "showYAxis": "Show Y Axis",
    "showYAxisTitle": "Show Y Axis Title",
    "showXGridlines": "Show X Gridlines",
    "showYGridlines": "Show Y Gridlines",
    "showDataLabels": "Show Data Labels",
    "showDataPoints": "Show Data Points",
    "stacked": "Stacked",
    "newView": "New",
    "calendarView": "Calendar View",
    "dayView": "Day View",
    "weekView": "Week View",
    "monthView": "Month View",
    "closeSpace": "Remove from Focus",
    "customView": "Custom View",
    "detailsView": "Details View",
    "catalogView": "Catalog View",
    "galleryView": "Gallery View",
    "deleteContext": "Delete Context",
    "openSpace": "Open",
    "setNone": "None",
    "applyItems": "Apply to Items in Folder",
    "rename": "Rename",
    "changeToFolderNote": "Convert to Folder Note",
    "moveFile": "Move File to...",
    "duplicate": "Make a copy",
    "edit": "Edit",
    "delete": "Delete",
    "getHelp": "Make.md Community",
    "openVault": "Open Another Vault",
    "obSettings": "Obsidian Settings",
    "collapseAllSections": "Collapse All Spaces",
    "expandAllSections": "Expand All Spaces",
    "collapseAllFolders": "Collapse All Folders",
    "settings": "Settings",
    "none": "None",
    "tableView": "Table View",
    "cardView": "Card View",
    "boardView": "Board View",
    "listView": "List View",
    "flowView": "Flow View",
    "sortBy": "Sort",
    "filters": "Filters",
    "clearFilters": "Clear Filters",
    "hide": "Hide",
    "unhideFields": "Unhide All Fields",
    "removeFromSpace": "Unpin from ${1}",
    "editCode": "Edit Code",
    "editProperties": "Edit Properties",
    "properties": "Properties",
    "deleteProperty": "Delete Property",
    "hideProperty": "Hide Property",
    "unhideProperty": "Unhide Property",
    "sortAscending": "Sort Ascending",
    "sortDescending": "Sort Descending",
    "deleteRow": "Delete Item",
    "customSort": "Custom Sort",
    "groupSpaces": "Group Spaces",
    "recursiveSort": "Apply to Subfolders",
    "fileNameSortAlphaAsc": "File Name (A to Z)",
    "fileNameSortAlphaDesc": "File Name (Z to A)",
    "fileNameSortNumericalAsc": "File Name (1 to 9)",
    "fileNameSortNumericalDesc": "File Name (9 to 1)",
    "createdTimeSortAsc": "Created Time (new to old)",
    "createdTimeSortDesc": "Created Time (old to new)",
    "modifiedTimeSortAsc": "Modified Time (new to old)",
    "modifiedTimeSortDesc": "Modified Time (old to new)",
    "sizeSortAsc": "Size (smallest to largest)",
    "sizeSortDesc": "Size (largest to smallest)",
    "changeColor": "Color",
    "changePropertyType": "Change Type",
    "folder": "Folder",
    "syncToContext": "Add Property to Context",
    "setIcon": "Set Sticker",
    "copyEmbedLink": "Copy Embed Link",
    "moveUp": "Move Up",
    "moveDown": "Move Down",
    "insertAbove": "Insert Above",
    "insertBelow": "Insert Below",
    "toggleReadMode": "Toggle Read Mode",
    "toggleFullWidth": "Toggle Full Width",
    "showWarnings": "Show Warnings",
    "openFilePane": "Open File Pane",
    "openNativeMenu": "More Options",
    "revealInDefault": "Reveal in Finder",
    "revealInExplorer": "Reveal in Explorer",
    "showHeader": "Show Header",
    "hideHeader": "Hide Header"
  },
  "editor": {
    "linkName": "${1} Link",
    "linkThumbnail": "${1} Thumbnail",
    "linkSticker": "${1} Sticker",
    "rows": "Rows",
    "columns": "Columns",
    "scaleToFit": "Scale to Fit",
    "scaleToFill": "Scale to Fill",
    "catalog": "Catalog",
    "gallery": "Gallery",
    "grid": "Grid",
    "fit": "Fit",
    "fill": "Fill",
    "stroke": "Stroke",
    "strokeNone": "None",
    "strokeSolid": "Solid",
    "strokeDotted": "Dotted",
    "strokeDashed": "Dashed",
    "size": "Size",
    "gap": "Gap",
    "marginLeft": "Left",
    "marginTop": "Top",
    "marginRight": "Right",
    "marginBottom": "Bottom",
    "minimize": "Minimize",
    "paddingLeft": "Left",
    "paddingTop": "Top",
    "paddingRight": "Right",
    "paddingBottom": "Bottom",
    "unlinkProperty": "Unlink Property",
    "linkedProperty": "Linked Property",
    "linkProperty": "Link Property",
    "currentSpace": "Current Space",
    "opacity": "Opacity",
    "shadowSpread": "Spread",
    "shadowBlur": "Blur",
    "width": "Width",
    "height": "Height",
    "margin": "Margin",
    "padding": "Padding",
    "bold": "Bold",
    "italic": "Italic",
    "underline": "Underline",
    "alignLeft": "Align Left",
    "alignCenter": "Align Center",
    "alignRight": "Align Right",
    "alignJustify": "Align Justify",
    "numberOfLines": "Lines",
    "createVerticalSection": "Create Vertical Section",
    "createHorizontalSection": "Create Horizontal Section"
  },
  "buttons": {
    "close": "Close",
    "back": "Back",
    "add": "Add",
    "import": "Import",
    "cancel": "Cancel",
    "create": "Create",
    "togglePin": "Toggle Pin",
    "refresh": "Refresh",
    "showHidden": "Show Hidden",
    "alias": "Alias",
    "addFilter": "Add Filter",
    "loadMore": "Load More",
    "addCondition": "Add Condition",
    "customize": "Customize",
    "moreOptions": "More Options",
    "saveProperty": "Save Property",
    "newNote": "New Note",
    "changeIcon": "Sticker",
    "removeIcon": "Remove Sticker",
    "addIcon": "Add Sticker",
    "addCover": "Add Cover",
    "changeBanner": "Change Cover",
    "changeBannerShort": "Cover",
    "removeBanner": "Remove Cover",
    "rename": "Change Name",
    "createFolder": "New Folder",
    "createCanvas": "New Canvas",
    "addIntoSpace": "Pin Item",
    "addSmartSearch": "Add Join",
    "editProperty": "Edit Property",
    "addContext": "Add Tag",
    "delete": "Delete",
    "toggleFlow": "Toggle Flow",
    "openFlow": "Open Flow",
    "hideFlow": "Hide Flow",
    "addToSpace": "Pin File to...",
    "addToSpaceShort": "Pin",
    "saveTemplate": "Make into template",
    "tag": "Tag",
    "convertTable": "Convert to Markdown",
    "cutTable": "Cut Table",
    "deleteTable": "Delete From Note",
    "addFile": "Add File",
    "renameView": "Rename View",
    "save": "Save",
    "run": "Run",
    "export": "Export",
    "move": "Move",
    "openOverview": "Open Overview",
    "addTime": "Add Time",
    "addFromExisting": "Add from Existing"
  },
  "metadataTypes": {
    "fileName": "File Name",
    "contexts": "Contexts",
    "isFolder": "Is Folder",
    "path": "Path",
    "folder": "Folder",
    "sticker": "Sticker",
    "color": "Color",
    "created": "Created",
    "lastModified": "Last Modified",
    "extension": "Extension",
    "size": "Size",
    "tags": "Tags",
    "inlinks": "Linked Mentions",
    "outlinks": "Links",
    "label": "Label",
    "fileMetadata": "File Metadata",
    "frontmatter": "Frontmatter"
  },
  "filterTypes": {
    "contains": "contains",
    "notContains": "does not contain",
    "is": "is",
    "isNot": "is not",
    "before": "before",
    "after": "on or after",
    "anyOf": "is any of",
    "noneOf": "is none of",
    "checked": "is checked",
    "unchecked": "is unchecked",
    "isNotEmpty": "is not empty",
    "isEmpty": "is empty",
    "isSameDate": "is same day as",
    "isSameDateAsToday": "is today"
  },
  "sortTypes": {
    "alphaAsc": "A to Z",
    "alphaDesc": "Z to A",
    "earliest": "Earliest",
    "latest": "Latest",
    "checkAsc": "Checked → Unchecked",
    "checkDesc": "Unchecked → Checked",
    "itemsAsc": "Least Items",
    "itemsDesc": "Most Items"
  },
  "properties": {
    "aggregate": {
      "label": "Aggregate",
      "description": "Aggregate functions to calculate values"
    },
    "flex": {
      "label": "Flex",
      "description": "Flexible field to display any type of data"
    },
    "audio": {
      "label": "Audio"
    },
    "text": {
      "label": "Text",
      "description": "Text field"
    },
    "number": {
      "label": "Number",
      "description": "Number field with optional unit"
    },
    "boolean": {
      "label": "Yes/No",
      "description": "Yes or No toggle to indicate the status"
    },
    "date": {
      "label": "Date",
      "description": "Select a date from a calendar"
    },
    "option": {
      "label": "Option",
      "description": "Select one or multiple option from a list"
    },
    "file": {
      "label": "File"
    },
    "link": {
      "label": "Link",
      "description": "Link to another note or a website"
    },
    "tags": {
      "label": "Tags",
      "description": "Use tags to quickly organize your items"
    },
    "object": {
      "label": "Object",
      "description": "Store any complex objects"
    },
    "context": {
      "label": "Context",
      "description": "Context property type"
    },
    "image": {
      "label": "Image",
      "description": "Select any image from your system or from the internet"
    },
    "color": {
      "label": "Color",
      "description": "Use colors to label your items or status"
    },
    "space": {
      "label": "Context",
      "description": "Link to a context"
    },
    "icon": {
      "label": "Sticker",
      "description": "Use stickers to uniquely label your items or status"
    },
    "super": {
      "label": "Super Property",
      "performAction": "Perform Action",
      "whenClicked": "When Clicked"
    },
    "fileProperty": {
      "name": "Name",
      "label": "Formula",
      "createdTime": "Created",
      "modifiedTime": "Last Edited",
      "sticker": "Sticker",
      "links": "Links",
      "tags": "Tags",
      "spaces": "Spaces",
      "extension": "Extension",
      "size": "Size",
      "parentFolder": "Folder",
      "description": "Use a formula to dynamically display a property"
    }
  },
  "views": {
    "navigator": "Navigator",
    "explorer": "Explorer"
  },
  "labels": {
    "base0": "Base0",
    "base10": "Base10",
    "base20": "Base20",
    "base30": "Base30",
    "base40": "Base40",
    "base50": "Base50",
    "base60": "Base60",
    "base70": "Base70",
    "base80": "Base80",
    "base90": "Base90",
    "base100": "Base100",
    "installSpaceKit": "Install Space Kit",
    "filesCount": "{$1} Files",
    "someFilesHaveInvalidNames": "Some Files Have Invalid Names",
    "placeholder": "Type '${1}' for commands",
    "toAppendLinkToTheFile": "to append link to the file",
    "notePlaceholder": "New Note for ${1}",
    "noNotesInside": "No Notes Inside",
    "today": "Today",
    "startTimeProperty": "Start Time Property",
    "endTimeProperty": "End Time Property",
    "startOfDay": "Start Of Day",
    "endOfDay": "End Of Day",
    "itemsSelected": "${1} Selected",
    "createATemplateToGetStarted": "Create a template to get started",
    "iconCount": "${1} icons",
    "iconsIn": "Icons in ${1}",
    "showingFirst": "Showing first ${1} of ${2} icons",
    "createNewItem": "Create New Item",
    "autosaveFailed": "Auto-save failed:",
    "editTitle": "Edit title",
    "removeOption": "Remove option",
    "unknownTransformationError": "Unknown transformation error",
    "center": "Center",
    "position": "Position",
    "top": "Top",
    "bottom": "Bottom",
    "value": "Value",
    "pounds": "Pounds",
    "all": "All",
    "duplicateTable": "Duplicate Table",
    "aggregateBy": "Aggregate By",
    "editFormula": "Edit Formula",
    "editObject": "Edit Object",
    "properties": "Properties",
    "newAction": "Action",
    "newTable": "New Table",
    "template": "New Template",
    "rename": "Rename",
    "default": "Default",
    "style": "Style",
    "done": "Done",
    "reposition": "Reposition",
    "tables": "Tables",
    "createSection": "New Folder",
    "createNote": "New Note",
    "select": "Select",
    "pinnedItems": "Pinned Items",
    "making": "Making...",
    "findStickers": "Find Sticker",
    "joinItemsFrom": "Join items from",
    "notIncludingSubfolders": "Not including subfolders",
    "includingSubfolders": "Including subfolders",
    "createNewItemsUsing": "Create new items using",
    "withName": "with name",
    "createTemplate": "Create Template",
    "editTemplate": "Edit Template",
    "noTemplatesFound": "No templates found",
    "createFirstTemplate": "Create your first global template",
    "syncWarnings": "The following issues may affect the synchronization of your files. Please review and resolve them.",
    "noWarnings": "No warnings",
    "resolve": "Resolve",
    "ignore": "Ignore",
    "loadingTemplates": "Loading templates...",
    "selectNote": "Select Note",
    "selectIcon": "Select Sticker",
    "selectSpace": "Select Space",
    "styleSmall": "Small",
    "styleMedium": "Medium",
    "styleLarge": "Large",
    "hiddenFilePattern": "Name, Suffixes and Extension",
    "hiddenFileSpecific": "Exclude specific files and folders",
    "textPlaceholder": "Enter Text",
    "noFile": "File does not exist yet. Click to create.",
    "blinkPlaceholder": "Search for notes, spaces...",
    "searchPlaceholder": "Type to search...",
    "contextItemSelectPlaceholder": "Find Item",
    "linkItemSelectPlaceholder": "Find or Create Note",
    "pinNotePlaceholder": "Select a Note or Space to Pin",
    "optionItemSelectPlaceholder": "Select Option",
    "tagItemSelectPlaceholder": "Find Tag",
    "spaceSelectPlaceholder": "Select any Folder or Tag",
    "propertyItemSelectPlaceholder": "Select Property",
    "sortItemSelectPlaceholder": "Select Sort",
    "filterItemSelectPlaceholder": "Select Filter",
    "newPaletteName": "New palette name...",
    "newProperty": "New Property",
    "newPropertyShort": "New Property",
    "propertyType": "Type",
    "propertyDynamic": "Dynamic",
    "propertyValueSpace": "Space",
    "propertyValueReference": "Related Property",
    "propertyValueAggregate": "Aggregate Property",
    "propertyValueLinked": "Linked Property",
    "propertyValueLinkedPlaceholder": "Add/Select Property",
    "propertyLookup": "Edit Formula",
    "existingFrontmatter": "Existing Property",
    "dateFormat": "Date Format",
    "numberFormat": "Number Format",
    "editOptions": "Edit Options",
    "checkedSticker": "Checked",
    "uncheckedSticker": "Unchecked",
    "indeterminateSticker": "Unset",
    "propertyFileProp": "Property",
    "multiple": "Multiple",
    "hiddenFiles": "Hidden Files",
    "colors": "Colors",
    "stickers": "Stickers",
    "globalTemplates": "Global Templates",
    "loadingPalettes": "Loading palettes...",
    "loadingStickerSets": "Loading sticker sets...",
    "manageHiddenFiles": "Manage Hidden Files",
    "addStickerSet": "Add Sticker Set",
    "iconLibrary": "Icon library",
    "emojiLibrary": "Emoji library",
    "builtin": "Built-in",
    "custom": "Custom",
    "dropIconsHere": "Drop icons here to create a new icon set",
    "dropPalettesHere": "Drop JSON palette files here to import",
    "addExtension": "Add Rule",
    "saveView": "Save View",
    "renameView": "Rename View",
    "backlinks": "Backlinks",
    "spaces": "Spaces",
    "content": "Content",
    "deleteSpace": "Delete Space",
    "deleteFiles": "Delete Files",
    "outgoingLinks": "Outgoing Links",
    "moveTo": "Move to",
    "addTo": "Pin to",
    "copyTo": "Copy to",
    "reorderIn": "Reorder in",
    "color": "Color",
    "backgroundColor": "Background",
    "layout": "Layout",
    "name": "Name",
    "alignment": "Alignment",
    "styles": "Styles",
    "actions": "Actions",
    "script": "Script",
    "formula": "Formula",
    "namePlaceholder": "Name",
    "insert": "Insert",
    "allDay": "all day",
    "templates": "Templates",
    "invalidMKitFile": "Invalid MKit File",
    "noFramesAvailable": "No frames available in this space kit",
    "calculate": "Calculate",
    "noVisualizationConfigured": "No visualization configured",
    "noVisualizationFound": "No visualization found",
    "saveFormula": "Save Formula",
    "selectSticker": "Select Sticker",
    "customize": "Customize",
    "items": "Items",
    "pins": "Pins",
    "joins": "Joins",
    "textStyle": "Text Style",
    "ungroup": "Ungroup",
    "duplicate": "Duplicate",
    "delete": "Delete",
    "list": "List",
    "none": "None",
    "auto": "auto",
    "addKit": "Add Kit",
    "kitLocation": "Kit Location",
    "addKitToSpace": "Add Kit to Space",
    "editPins": "Edit Pins",
    "editJoins": "Edit Joins",
    "editTables": "Edit Tables",
    "editTemplates": "Edit Templates",
    "exportToHTML": "Export to HTML",
    "applyToItems": "Apply to Items",
    "resetView": "Reset View",
    "resetViewDesc": "Reset the view to the default settings",
    "openASpace": "Open a Space",
    "openASpaceDesc": "Open existing folders and tags as a Space or create a new one",
    "setAsDefault": "Set as Default",
    "thisSpaceAndAllSubfolders": "This Space and All Subfolders",
    "changeCoverShort": "Change Cover",
    "link": "Link",
    "caption": "Caption",
    "colorScheme": "Color Scheme",
    "filesAndFolders": "Files and Folders",
    "mkitViewer": "MKit Viewer",
    "lucideIconLibraryForObsidian": "Lucide icon library for Obsidian",
    "emojiIconLibrary": "Emoji icon library",
    "gradients": "Gradients",
    "waypoint": "Waypoint",
    "empty": "Empty",
    "areRequiredForThisLayout": "are required for this layout",
    "showAll": "Show all",
    "limit": "Limit",
    "source": "Source",
    "sizing": "Sizing",
    "interactions": "Interactions",
    "card": "Card",
    "button": "Button",
    "enterTitleForNewItem": "Enter title for new item",
    "functions": "Functions",
    "suggestions": "Suggestions",
    "type": "Type",
    "makeAStaticWebVersionOf": "Make a static web version of",
    "others": "Others",
    "frameHasNoRows": "Frame has no rows",
    "series": "Series:",
    "size": "Size:",
    "label": "Label:",
    "xAxis": "X Axis",
    "yAxis": "Y Axis",
    "unknown": "Unknown",
    "title": "Title",
    "on": "On",
    "quarter": "Quarter",
    "off": "Off",
    "noDataProvided": "No data provided",
    "data": "Data",
    "root": "Root",
    "action": "Action",
    "checklist": "Checklist",
    "home": "Home",
    "frequency": "Frequency",
    "yearly": "Yearly",
    "monthly": "Monthly",
    "weekly": "Weekly",
    "daily": "Daily",
    "hourly": "Hourly",
    "minutely": "Minutely",
    "secondly": "Secondly",
    "until": "Until",
    "interval": "Interval",
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "sunday": "Sunday",
    "percent": "Percent",
    "sticker": "Sticker",
    "dollars": "Dollars",
    "euros": "Euros",
    "yuan": "Yuan",
    "rupees": "Rupees",
    "won": "Won",
    "francs": "Francs",
    "rands": "Rands",
    "krones": "Krones",
    "rubles": "Rubles",
    "dinars": "Dinars",
    "pesos": "Pesos",
    "rials": "Rials",
    "ringgits": "Ringgits",
    "drachmas": "Drachmas",
    "kuna": "Kuna",
    "forint": "Forint",
    "koruna": "Koruna",
    "dong": "Dong",
    "lira": "Lira",
    "lev": "Lev",
    "zloty": "Zloty",
    "kip": "Kip",
    "tughrik": "Tughrik",
    "rupiah": "Rupiah",
    "liters": "Liters",
    "seconds": "Seconds",
    "scientific": "Scientific",
    "header": "Header",
    "pageHeaderContainingBannerAndTitle": "Page header containing banner and title",
    "banner": "Banner",
    "slides": "Slides",
    "slide": "Slide",
    "delta": "Delta",
    "displayDataWithCustomFieldTypes": "Display data with custom field types",
    "expanded": "Expanded",
    "showFieldLabels": "Show Field Labels",
    "showFieldIcons": "Show Field Icons",
    "status": "Status",
    "subtitle": "Subtitle",
    "prefix": "Prefix",
    "completed": "Completed",
    "due": "Due",
    "fields": "Fields",
    "priority": "Priority",
    "newItemButton": "New Item Button",
    "showNewItemButton": "Show New Item Button",
    "rows": "Rows",
    "columns": "Columns",
    "masonry": "Masonry",
    "countdown": "Countdown",
    "tabs": "Tabs",
    "page": "Page",
    "checkbox": "Checkbox",
    "preview": "Preview",
    "toNavigate": "to navigate",
    "notImplemented": "Not implemented",
    "board": "Board",
    "nineToOne": "9 → 1",
    "xField": "X-Field",
    "yField": "Y-Field",
    "obsidianSyncCurrentlyWontSyncYourSpaces": "Obsidian Sync currently won't sync your Spaces",
    "obsidianSyncCurrentlyWontSyncYourSpaceViewsOrContext": "Obsidian Sync currently won't sync your Space Views or Context",
    "visualization": "Visualization",
    "blink": {
      "items": "Items",
      "recent": "Recent",
      "createNew": "Create New",
      "newNote": "New Note",
      "newSpace": "New Space",
      "results": "Results"
    }
  },
  "descriptions": {
    "defaultMakemlColorPaletteWithThemeColors": "Default Makeml Color Palette With Theme Colors",
    "monochromeColorPaletteWithBaseColors": "Monochrome Color Palette With Base Colors",
    "defaultGradientPaletteWithBeautifulGradients": "Default Gradient Palette With Beautiful Gradients",
    "softPastelColorsForGentleVisualizations": "Soft Pastel Colors For Gentle Visualizations",
    "installing": "Installing",
    "loopOverAList": "Loop Over A List",
    "loop": "Loop",
    "onlyContinueIfAConditionIsMet": "Only Continue If A Condition Is Met",
    "filter": "Filter",
    "useAFormulaToCalculateAResult": "Use A Formula To Calculate A Result",
    "formula": "Formula",
    "creating": "Creating",
    "pasteUrlsHereOnePerLine": "Paste Urls Here One Per Line",
    "pasteYourPaletteJsonHere": "Paste Your Palette Json Here",
    "createAndEditGlobalTemplatesStoredInSpacetemplatesFolder": "Create And Edit Global Templates Stored In Spacetemplates Folder",
    "searchForImagesInYourVaultOrPasteAUrl": "Search For Images In Your Vault Or Paste A Url",
    "getPropertyColor": "Get Property Color",
    "getTheColorForAPropertyValue": "Get The Color For A Property Value",
    "getPropertySticker": "Get Property Sticker",
    "getTheStickericonForAProperty": "Get The Stickericon For A Property",
    "parsePropertyValue": "Parse Property Value",
    "getContentsOfPath": "Get Contents Of Path",
    "getPropertiesOfPath": "Get Properties Of Path",
    "getPathLabel": "Get Path Label",
    "getTheLabelForAPath": "Get The Label For A Path",
    "getPathThumbnail": "Get Path Thumbnail",
    "getTheThumbnailForAPath": "Get The Thumbnail For A Path",
    "writeToPath": "Write To Path",
    "mode": "Mode",
    "append": "Append",
    "getItemsInsideOfPath": "Get Items Inside Of Path",
    "writeToFile": "Write To File",
    "setPathProperty": "Set Path Property",
    "setAPropertyOnAPath": "Set A Property On A Path",
    "showPathContextMenu": "Show Path Context Menu",
    "showContextMenuForAPath": "Show Context Menu For A Path",
    "executeAFormulaWithParameters": "Execute A Formula With Parameters",
    "index": "Index",
    "schema": "Schema",
    "createANewTable": "Create A New Table",
    "openTableRow": "Open Table Row",
    "openATableRow": "Open A Table Row",
    "showTableRowContextMenu": "Show Table Row Context Menu",
    "showContextMenuForATableRow": "Show Context Menu For A Table Row",
    "openTableRowEditModal": "Open Table Row Edit Modal",
    "openEditModalForATableRow": "Open Edit Modal For A Table Row",
    "openTableRowCreateModal": "Open Table Row Create Modal",
    "openCreateModalForANewTableRow": "Open Create Modal For A New Table Row",
    "field": "Field",
    "parseADateString": "Parse A Date String",
    "daysInMonth": "Days In Month",
    "getNumberOfDaysInAMonth": "Get Number Of Days In A Month",
    "formatADateWithAPattern": "Format A Date With A Pattern",
    "format": "Format",
    "getDateComponent": "Get Date Component",
    "getAComponentOfADate": "Get A Component Of A Date",
    "component": "Component",
    "dayOfWeek": "Day Of Week",
    "offsetADateByAnAmount": "Offset A Date By An Amount",
    "offset": "Offset",
    "getTheCurrentDate": "Get The Current Date",
    "getCurrentDate": "Get Current Date",
    "getARangeOfDates": "Get A Range Of Dates",
    "spaceActions": "Create actions that run when you press a button",
    "spaceLists": "Create lists to track data and organize them in your space",
    "spaceTemplates": "Create templates to quickly add items to your space",
    "smartSearch": "Automatically pin notes to this space based on a set of searches",
    "deleteSpace": "Deleting the space will also delete the folder and its contents.",
    "deleteFiles": "Delete ${1} files/folders and their contents?",
    "spaceProperties": "Define Properties for your Space Items",
    "templateNameFormula": "Template Name Formula",
    "hiddenFileOptions": "Hidden File Options",
    "maxStepsReachedYouCanChangeThisInSettings": "Max steps reached, you can change this in settings."
  },
  "notice": {
    "invalidStickerPackFile": "Invalid Sticker Pack File",
    "fileExists": "File Already Exists",
    "templateSaved": "Template saved to space: ",
    "tableDeleted": "Table removed from Note. You can find the table in the folder Space",
    "copyError": "Copy Error",
    "reload": "Reload",
    "kitDoesntExist": "Kit doesn't exist",
    "kitAdded": "Kit added",
    "error": "Error: ",
    "invalidKitURL": "Invalid Kit URL",
    "cantConvertNoteToSpace": "Can't Convert Note to Space",
    "newSpaceName": "New Space Name",
    "duplicateSpaceName": "Duplicate Space Name",
    "noPropertyName": "No Property Name",
    "duplicatePropertyName": "Duplicate Property Name",
    "palette": "Palette",
    "noPropertiesFound": "No Properties Found",
    "somethingWentWrong": "Something Went Wrong",
    "noExistingValues": "No Existing Values"
  },
  "settings": {
    "importUrls": "导入网址",
    "exportUrls": "导出网址",
    "removeImage": "移除图片",
    "color1": "颜色1",
    "dropColorPaletteHereToImport": "将调色板拖放到此处导入",
    "nameOfYourSystem": "系统名称",
    "manageGlobalTemplates": "管理全局模板",
    "stickerPack": "贴纸包",
    "other": "其他",
    "dropLanguagePackHereToImport": "将语言包拖放到此处导入",
    "flow": "流",
    "untitled": "未命名",
    "tags": "标签",
    "vault": "仓库",
    "title": "设置",
    "tooltips": {
      "deletePalette": "Delete palette",
      "resetToDefault": "Reset to default",
      "removeColor": "Remove color",
      "addColor": "Add color",
      "deleteStickerSet": "Delete sticker set",
      "addGradientStop": "Add gradient stop",
      "stopPosition": "Stop position (%)",
      "removeGradientStop": "Remove selected gradient stop",
      "importPalette": "Import palette from JSON",
      "exportPalette": "Export palette to JSON",
      "invalidPaletteFormat": "Invalid palette file format. Must have 'name' and 'colors' array.",
      "invalidJSON": "Invalid JSON format"
    },
    "ariaLabels": {
      "noColorApplied": "This element will have no color applied.",
      "closeOnboarding": "Close onboarding",
      "dataSource": "Data Source",
      "chartType": "Chart Type",
      "legendConfiguration": "Legend Configuration",
      "colorConfiguration": "Color Configuration",
      "close": "Close",
      "toggleXAxis": "Toggle X Axis",
      "toggleXAxisLabel": "Toggle X Axis Label",
      "toggleXGridlines": "Toggle X Gridlines",
      "toggleXAxisLine": "Toggle X Axis Line",
      "toggleStackedMode": "Toggle Stacked Mode",
      "toggleYAxis": "Toggle Y Axis",
      "toggleYAxisLabel": "Toggle Y Axis Label",
      "toggleDataLabels": "Toggle Data Labels",
      "toggleYGridlines": "Toggle Y Gridlines",
      "toggleYAxisLine": "Toggle Y Axis Line",
      "toggleLegend": "Toggle Legend",
      "legendPosition": "Legend Position",
      "legendAlignment": "Legend Alignment",
      "toggleLineSmoothing": "Toggle Line Smoothing",
      "toggleStroke": "Toggle Stroke",
      "toggleDataPoints": "Toggle Data Points",
      "toggleDonutChart": "Toggle Donut Chart"
    },
    "onboarding": {
      "welcome": "欢迎使用 Make.md",
      "welcomeDesc": "欢迎使用 Make.md！让我们配置您的基本设置以开始使用。",
      "walkthrough": "我们将浏览最重要的选项以自定义您的体验。",
      "coreFeatures": "核心功能",
      "enableNavigator": "启用导航器（侧边栏文件浏览器）",
      "enableNavigatorDesc": "在侧边栏中显示增强的文件导航器",
      "enableSpaceViews": "启用空间视图",
      "enableSpaceViewsDesc": "创建自定义视图并在空间中组织内容",
      "enableContexts": "启用上下文和属性",
      "enableContextsDesc": "向笔记添加结构化数据和元数据",
      "interfacePreferences": "界面偏好",
      "showBanners": "显示笔记横幅",
      "showBannersDesc": "在笔记顶部显示横幅图片",
      "showFileIcons": "显示文件图标",
      "showFileIconsDesc": "在文件和文件夹旁边显示自定义图标",
      "systemName": "系统名称",
      "systemNameDesc": "自定义您的工作区名称",
      "previous": "上一步",
      "next": "下一步",
      "skipTour": "跳过教程",
      "getStarted": "开始使用"
    },
    "categories": {
      "core": "核心",
      "appearance": "外观",
      "system": "系统"
    },
    "sections": {
      "general": "常规",
      "navigator": "导航器",
      "appearance": "外观",
      "coverImage": "封面图片",
      "interaction": "偏好设置",
      "context": "上下文",
      "label": "标签",
      "tags": "标签",
      "space": "空间",
      "performance": "性能",
      "advanced": "高级",
      "folderNote": "文件夹笔记",
      "notes": "笔记",
      "assets": "资源",
      "language": "语言",
      "colors": "颜色",
      "stickers": "贴纸",
      "hidden": "隐藏文件",
      "basicsSettings": "基础设置"
    },
    "cacheIndex": {
      "name": "缓存搜索索引",
      "desc": "缓存索引以加快搜索结果"
    },
    "layoutVertical": "垂直",
    "layoutHorizontal": "水平",
    "sectionGeneral": "General",
    "sectionSidebar": "Spaces",
    "sectionEditor": "Maker Mode",
    "sectionFlow": "Flow",
    "sectionAdvanced": "Advanced",
    "sectionDataview": "Dataview",
    "sectionContext": "Context",
    "sectionStickers": "Labels",
    "sectionNavigator": "Navigator",
    "sectionDefault": "Default Spaces",
    "sectionSpaceView": "Space View",
    "sectionBlink": "Blink",
    "sectionInlineContext": "Inline Context",
    "sectionFlowBlock": "Flow Block",
    "sectionFlowMenu": "Flow Menu",
    "sectionFlowStyler": "Flow Styler",
    "experimental": {
      "name": "实验性",
      "desc": "实验性功能可能会发生变化，可能未针对性能进行优化"
    },
    "noteThumbnails": {
      "name": "笔记缩略图",
      "desc": "为笔记创建缩略图"
    },
    "imageThumbnails": {
      "name": "图片缩略图",
      "desc": "为图片创建缩略图以提升性能"
    },
    "hiddenExtensions": {
      "name": "隐藏扩展名",
      "desc": "要在导航器中隐藏的文件扩展名和名称"
    },
    "minimalThemeFix": {
      "name": "Minimal 主题修复",
      "description": "应用流行的 Minimal 主题修复"
    },
    "inlineStickerMenu": {
      "name": "内联贴纸",
      "desc": "通过输入 : 添加内联贴纸"
    },
    "openSpacesOnLaunch": {
      "name": "启动时打开导航器作为默认标签页",
      "desc": "在 Obsidian 启动时打开导航器标签页"
    },
    "overrideNativeMenu": {
      "name": "使用 Obsidian 上下文菜单",
      "desc": "显示 Obsidian 上下文菜单而不是 Make.md"
    },
    "editStickerInSidebar": {
      "name": "在侧边栏中编辑贴纸",
      "desc": "直接在侧边栏中编辑贴纸"
    },
    "notesPreview": {
      "name": "笔记预览",
      "desc": "显示笔记预览，可能会导致性能问题"
    },
    "spacesRightSplit": {
      "name": "导航器在右侧",
      "desc": "在右侧面板中打开导航器"
    },
    "defaultSpaceTemplate": {
      "name": "默认空间模板",
      "desc": "为新空间选择默认模板"
    },
    "datePickerTime": {
      "name": "日期选择器时间",
      "desc": "在日期选择器中默认选择时间"
    },
    "defaultDateFormat": {
      "name": "默认日期格式",
      "desc": "设置默认日期格式，例如：yyyy-MM-dd（参见 https://date-fns.org/v2.30.0/docs/format）"
    },
    "defaultTimeFormat": {
      "name": "默认时间格式",
      "desc": "设置默认时间格式，例如：h:mm a（参见 https://date-fns.org/v2.30.0/docs/format）"
    },
    "autoAddContextsToSubtags": {
      "name": "将属性应用于子标签",
      "desc": "自动将上下文属性应用于子标签"
    },
    "newNotePlaceholder": {
      "name": "新笔记占位符",
      "desc": "新笔记的默认名称，适用于导航器按钮和新建笔记命令"
    },
    "folderIndentationLines": {
      "name": "显示文件夹缩进线",
      "desc": "打开后在文件夹左侧显示一条线以指示缩进"
    },
    "folderNoteLocation": {
      "name": "文件夹笔记位置在文件夹内",
      "desc": "打开后文件夹笔记位于文件夹内，关闭后位于文件夹外"
    },
    "folderViewDefault": {
      "name": "默认显示文件夹笔记",
      "desc": "打开文件夹时默认显示文件夹笔记"
    },
    "internalLinkFlowEditor": {
      "name": "在链接上显示切换按钮以打开流编辑器",
      "desc": "打开后可在内联链接中直接切换流块"
    },
    "internalLinkSticker": {
      "name": "在链接上显示贴纸",
      "desc": "打开后可在内部链接旁边直接切换显示的贴纸"
    },
    "saveAllContextToFrontmatter": {
      "name": "将上下文字段同步到前置元数据",
      "desc": "打开后自动将所有上下文字段保存到前置元数据字段，而不仅仅是现有的前置元数据字段。"
    },
    "syncFormulaToFrontmatter": {
      "name": "将公式字段同步到前置元数据",
      "desc": "打开后将计算的公式值保存到前置元数据字段。"
    },
    "spaceSubFolder": {
      "name": "空间文件夹名称",
      "desc": "空间的文件夹名称"
    },
    "basics": {
      "name": "Make.md 基础",
      "desc": "启用 Make.md 基础功能，包括样式器和流块"
    },
    "spacesFolder": {
      "name": "标签空间文件夹",
      "desc": "标签空间的文件夹名称"
    },
    "inlineContext": {
      "name": "笔记标题",
      "desc": "显示标题以显示标签和属性"
    },
    "banners": {
      "name": "封面图片",
      "desc": "为笔记和空间显示封面图片"
    },
    "inlineContextProperties": {
      "name": "在标题中显示上下文属性",
      "desc": "在笔记和空间的标题中显示属性"
    },
    "inlineContextExpanded": {
      "name": "自动展开上下文属性",
      "desc": "打开笔记时展开内联上下文部分"
    },
    "inlineContextNameLayout": {
      "name": "标题和贴纸布局",
      "desc": "内联上下文中内联标题和贴纸的布局"
    },
    "hideFrontmatter": {
      "name": "隐藏上下文属性",
      "desc": "在 Obsidian 属性面板中隐藏您在上下文中添加的属性"
    },
    "autoOpenFileContext": {
      "name": "自动打开资源管理器",
      "desc": "在右侧面板中自动打开资源管理器面板"
    },
    "enableFolderNote": {
      "name": "启用文件夹笔记",
      "desc": "在文件夹页面中访问文件夹笔记，并从空间中隐藏文件夹笔记"
    },
    "folderNoteName": {
      "name": "文件夹笔记名称",
      "desc": "文件夹笔记的名称，保持空白以使用与文件夹相同的名称"
    },
    "expandFolderOnClick": {
      "name": "自动展开文件夹",
      "desc": "点击时自动展开文件夹"
    },
    "filePreviewOnHover": {
      "name": "悬停预览",
      "desc": "按住 Control/Command 键时悬停预览"
    },
    "revealActiveFile": {
      "name": "显示活动文件",
      "desc": "在导航器中自动显示活动文件"
    },
    "contextEnabled": {
      "name": "上下文",
      "desc": "上下文允许您完全控制文件的元数据"
    },
    "navigatorEnabled": {
      "name": "导航器",
      "desc": "导航器允许您创建和组织空间"
    },
    "spacesStickers": {
      "name": "贴纸",
      "desc": "使用表情符号让查找笔记更容易"
    },
    "spacesUseAlias": {
      "name": "别名",
      "desc": "使用别名元数据在导航器中显示"
    },
    "spacesDisablePatch": {
      "name": "兼容模式",
      "desc": "这将提高使用导航器时插件的兼容性，但会关闭从面包屑链接到空间的功能"
    },
    "deleteFileOption": {
      "name": "删除文件选项",
      "desc": "选择您希望如何删除文件"
    },
    "spacesDeleteOptions": {
      "permanent": "永久删除",
      "trash": "移动到 Obsidian 废纸篓",
      "system-trash": "移动到系统废纸篓"
    },
    "flowState": {
      "name": "流状态",
      "desc": "切换流状态"
    },
    "showRibbon": {
      "name": "应用功能区",
      "desc": "显示/隐藏左侧菜单（即功能区）"
    },
    "vaultSelector": {
      "name": "仓库选择器",
      "desc": "显示/隐藏底部的仓库选择器"
    },
    "spaceViewEnabled": {
      "name": "空间",
      "desc": "使用属性和视图自定义您的文件夹和标签"
    },
    "defaultSpaces": {
      "name": "默认空间",
      "desc": "用于快速组织仓库的推荐空间"
    },
    "homeSpace": {
      "name": "主页空间",
      "desc": "一个易于访问的空间，您可以在其中添加/组织其他空间"
    },
    "enableDefaultSpaces": {
      "name": "标签空间",
      "desc": "为您的每个标签自动创建空间"
    },
    "readableLineWidth": {
      "name": "可读行宽",
      "desc": "使用可读行宽"
    },
    "sidebarTabs": {
      "name": "侧边栏标签",
      "desc": "显示/隐藏其他侧边栏标签"
    },
    "spacesPerformance": {
      "name": "导航器滚动性能",
      "desc": "为导航器开启性能模式，可能会影响滚动外观。需要重启"
    },
    "indexSVG": {
      "name": "使用 SVG 作为贴纸",
      "desc": "将仓库中的任何 svg 文件用作贴纸"
    },
    "language": {
      "name": "自定义界面语言",
      "desc": "修改界面中的任何文本。更改需要重新加载才能生效。",
      "loadingSettings": "正在加载语言设置...",
      "exportJSON": "导出 JSON",
      "importJSON": "导入 JSON",
      "importJSONDesc": "在此处粘贴您的语言 JSON。只会导入修改过的值。",
      "pasteJSONPlaceholder": "在此处粘贴您的 JSON...",
      "import": "导入",
      "cancel": "取消",
      "copied": "已复制！",
      "resetAll": "重置全部",
      "search": "搜索",
      "searchDesc": "按键或文本值搜索",
      "showingCount": "显示 {{filtered}} / {{total}} 个字符串",
      "original": "原始",
      "invalidJSON": "无效的 JSON 格式。请检查您的输入。"
    },
    "inlineStyler": {
      "name": "流样式器",
      "desc": "选择文本以添加样式"
    },
    "inlineStylerColor": {
      "name": "文本和高亮颜色 🧪",
      "desc": "选择文本颜色和高亮颜色（由于 HTML 和 Obsidian 的限制，这在未来可能会改变）"
    },
    "spaceRowHeight": {
      "name": "行高",
      "desc": "导航器中每行的高度（像素），默认为 29"
    },
    "mobileSpaceRowHeight": {
      "name": "行高 - 移动设备",
      "desc": "移动设备导航器中每行的高度（像素），默认为 40"
    },
    "contextPagination": {
      "name": "表格视图分页",
      "desc": "表格视图中每页的项目数"
    },
    "bannerHeight": {
      "name": "封面高度",
      "desc": "笔记或空间的封面高度，默认为 200"
    },
    "makeChar": {
      "name": "流菜单触发器",
      "desc": "打开流菜单的字符"
    },
    "mobileMakeBar": {
      "name": "流样式器（移动设备）",
      "desc": "替换移动工具栏"
    },
    "editorMarkSans": {
      "name": "无 Markdown 🧪",
      "desc": "使用不带 Markdown 的编辑器。"
    },
    "editorMakePlaceholder": {
      "name": "流菜单提示文本",
      "desc": "显示如何打开流菜单快捷键的提示文本"
    },
    "blinkEnabled": {
      "name": "Blink",
      "desc": "搜索和编辑笔记的更快方式"
    },
    "editorMakeMenu": {
      "name": "流菜单",
      "desc": "打开流菜单以快速添加内容"
    },
    "editorMakeMenuTrigger": {
      "name": "流菜单快捷键",
      "desc": "使用流菜单的触发键"
    },
    "editorFlowReplace": {
      "name": "流块",
      "desc": "在流块中打开内部链接或切换嵌入内容。"
    },
    "editorFlowStyle": {
      "name": "流块样式",
      "desc": "为您的流块选择主题",
      "seamless": "无缝",
      "minimal": "极简"
    },
    "contextCreateUseModal": {
      "name": "使用模态框创建项目",
      "desc": "使用模态框在上下文中创建新项目"
    },
    "changeTheSyncSettingsToIncludeUnsupportedFileTypes": {
      "name": "更改同步设置以包含不支持的文件类型",
      "desc": "更改同步设置以包含不支持的文件类型"
    },
    "noVisualizationConfigured": {
      "name": "未配置可视化",
      "desc": "未配置可视化"
    },
    "maxStepsReachedYouCanChangeThisInSettings": {
      "name": "已达到最大步骤数，您可以在设置中更改此设置。",
      "desc": "已达到最大步骤数，您可以在设置中更改此设置。"
    }
  },
  "colors": {
    "red": "Red",
    "pink": "Pink",
    "orange": "Orange",
    "yellow": "Yellow",
    "green": "Green",
    "turquoise": "Turquoise",
    "teal": "Teal",
    "blue": "Blue",
    "purple": "Purple",
    "brown": "Brown",
    "charcoal": "Charcoal",
    "gray": "Gray",
    "gold": "Gold",
    "plum": "Plum",
    "khaki": "Khaki",
    "moccasin": "Moccasin",
    "lavender": "Lavender"
  },
  "units": {
    "celsius": "Celsius",
    "fahrenheit": "Fahrenheit",
    "yen": "Yen",
    "baht": "Baht",
    "ounces": "Ounces",
    "miles": "Miles",
    "feet": "Feet",
    "inches": "Inches",
    "centimeters": "Centimeters",
    "millimeters": "Millimeters",
    "kilograms": "Kilograms",
    "grams": "Grams"
  },
  "formulas": {
    "prop": "Get the value of a property",
    "slice": "Get a part of a text",
    "if": "If condition is true return the first argument else return the second",
    "ifs": "If the first condition is true return the first argument else check the next condition",
    "empty": "Check if a list is empty",
    "length": "Get the length of a list",
    "values": "Get the number of values in a list",
    "uniques": "Get the number of unique values in a list",
    "substring": "Get a substring of a string",
    "startsWith": "Check if a string starts with another string",
    "contains": "Check if a string contains another string",
    "test": "Test a string with a regex",
    "match": "Match a string with a regex",
    "replace": "Replace a string with another string",
    "replaceAll": "Replace all occurences of a string with another string",
    "lower": "Convert a string to lowercase",
    "upper": "Convert a string to uppercase",
    "repeat": "Repeat a string",
    "format": "Format a value to string",
    "toNumber": "Convert a value to a number",
    "now": "Get the current date",
    "minute": "Get the minutes of a date",
    "hour": "Get the hours of a date",
    "day": "Get the day of a date",
    "date": "Get the date of a date",
    "week": "Get the week of a date",
    "month": "Get the month of a date",
    "year": "Get the year of a date",
    "pad": "Pad a number with text",
    "range": "Get the difference between the largest and smallest from a list of numbers",
    "latest": "Get the latest date of a list of dates",
    "earliest": "Get the earliest date of a list of dates",
    "dateRange": "Get the date range of a list of dates",
    "dateAdd": "Add an amount to a date",
    "dateSubtract": "Subtract an amount from a date",
    "dateBetween": "Get the difference between two dates",
    "spaceItems": "Get the items inside of a path",
    "spaces": "Get the spaces the path is inside of",
    "timeStamp": "Get the timestamp of a date",
    "at": "Get an element at a specific index",
    "first": "Get the first element of a list",
    "last": "Get the last element of a list",
    "concat": "Concatenate two lists",
    "sort": "Sort a list",
    "reverse": "Reverse a list",
    "join": "Turn a list into text separator",
    "includes": "Check if a list includes a value",
    "split": "Split text into a list using a separator",
    "formatDate": "Format a date into text",
    "parseDate": "Transform date from text",
    "find": "Find an element in a list",
    "findIndex": "Find the index of an element in a list",
    "filter": "Filter a list based on a condition",
    "map": "Change all the values in a list based on a formula",
    "some": "Check if some elements in a list are true",
    "every": "Check if every element in a list is true",
    "flat": "Flatten a list of lists into a single list",
    "path": "Get the path object of a path",
    "let": "Define a variable to use in a formula",
    "lets": "Define multiple variables to use in a formula"
  }
};
